### ISSUE TITLE
Wanted API — FBI

### ISSUE THREAD

**Issue by kaialane** [api-search/inbox#15]
The FBI Wanted API is designed to help developers easily get information on the FBI Wanted program. The API is a simple REST endpoint that accepts query parameters for options and returns application/json responses. ~ https://www.fbi.gov/wanted/api

**Comment by kinlane** [comment]
An [APIs.json](https://github.com/api-search/federal-bureau-of-investigation/blob/main/apis.yml) and [OpenAPI](https://github.com/api-search/federal-bureau-of-investigation/blob/main/openapi.yml) were created for this API in a [dedicated repository for the FBI](https://github.com/api-search/federal-bureau-of-investigation/tree/main).

The APIs.io search engine will crawl the repo and ingest the APIs.json and the API will be added to the search engine.
